### ISSUE TITLE
IntelliJ support

### ISSUE THREAD

**Issue by nickspacek** [franzbecker/gradle-lombok#23]
It would be great for this to have the option to install the IntelliJ plugin, though I realize it is unofficial. Additionally, if the "idea" plugin is also applied to a project it would be great to have this plugin automatically enable the Annotation Processing when imported.

**Comment by franzbecker** [comment]
I'm not sure if this is within the scope of this plugin. The `installLombok` task forwards the functionality towards Lombok itself, so it does not implement it itself. Maybe this would be a good issue for the Lombok core project (https://github.com/rzwitserloot/lombok)?

Your second point makes sense but I've never used Lombok + IntelliJ so a contribution would be appreciated :)

**Comment by tonit** [comment]
As far as i understand, this is "only" about integration with the (3rd party) lombok intellij. correct?
I arrived in this issue because the Readme here warns about using 1.12 with intellij and recommends 1.11.
I am now interested:
- is this also true for 1.13?
- and what is the problem with 1.12 that 1.11 does not have? Which Issue Nr. is the problem?

**Comment by franzbecker** [comment]
Hi @tonit 

- it's no longer true for 1.13
- the issue was this change https://github.com/franzbecker/gradle-lombok/pull/35/files but was probably a bug in the IntelliJ Gradle integration or the IntelliJ Lombok plugin (not sure)

**Comment by akoidan** [comment]
What's the status on this? I'm getting the error bellow, tho I have Idea lomok plugin installed, and enabled it, and have annotation processors enabled in settings.

![image](https://user-images.githubusercontent.com/1336703/40578897-2ba05bcc-6125-11e8-9435-3689b7e364e3.png)

`gradle build` works ok tho

**Comment by k3b** [comment]
I just verified that Lombok works with intellij-2019.1.3. 

I Followed these instructions  https://projectlombok.org/setup/android to install

In IntelliJ under Settings/Build,Execution,Deployment/Compiler/AnnotationProcessors you have to enable the AnnotationProcessing

In AndroidStudio-3.4.2 i did not find this option. I did not test if it worked there

This was my executed code

build.gradle

	plugins {
	    id "io.franzbecker.gradle-lombok" version "3.1.0"
	    id 'java'
	}

	apply plugin: "io.franzbecker.gradle-lombok"

	group 'de.k3b.test'
	version '1.0-SNAPSHOT'

	sourceCompatibility = 1.8

	repositories {
	    mavenCentral()
	}

	dependencies {
	    testCompile group: 'junit', name: 'junit', version: '4.12'
	    
	    compileOnly 'org.projectlombok:lombok:1.18.8'

	    annotationProcessor 'org.projectlombok:lombok:1.18.8'
	}

Main.java

        package de.k3b.test;

	import lombok.Data;

	import static java.lang.System.out;

	@Data
	public class Main {

	    private String message;

	    public static void main(String[] args) {
		Main main = new Main();

		// setter generated via annotation @lombok.Data and dependencies {annotationProcessor 'org.projectlombok:lombok:1.18.8'}
		main.setMessage("hallo world\n");

		out.print(main.getMessage());
		out.print("main.toString() = " + main.toString());
		// write your code here
	    }
	}

Console output

>   hallo world
>  main.toString() = Main(message=hallo world
>  )

---

> it would be great to have this plugin automatically enable the Annotation Processing when imported.

I had to do this manually :-(

**Comment by franzbecker** [comment]
Closing this as won't fix as I moved the plugin to maintenance mode. Any contributions are more than welcome! I will still fix major bugs and review PRs.
